services:
  argos_main: 
    container_name: argos_main
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
    entrypoint: ["sleep", "infinity"]
    restart: unless-stopped
    volumes:
      - argos_data:/argos_data
    networks: 
      - argos_network
    
  db:
    container_name: argos_postgres-db
    image: postgres:latest
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./api/sql/schema:/docker-entrypoint-initdb.d 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - argos_network

  migrate:
    container_name: argos_migrate
    build: ./api/migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
    volumes:
      - ./api/sql/schema:/migrations
    networks:
      - argos_network
    restart: "no"

volumes: 
  postgres_data:
  argos_data:

networks: 
  argos_network:
    driver: bridge