// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: domains.sql

package database

import (
	"context"
)

const insertDomain = `-- name: InsertDomain :one
INSERT INTO domains (
    id, 
    name,
    created_at,
    updated_at
)
VALUES (
    gen_random_uuid(), $1, NOW(), NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) InsertDomain(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, insertDomain, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
